"""Core data contracts shared by every CogAlpha component.

An *alpha* in this system is a Python source string defining exactly one
top-level function that maps an OHLCV panel to a factor series.  Keeping the
alpha as **code** (rather than a formula tree) is the paper's central
representational choice: it aligns with what an LLM generates natively and lets
a candidate use branches, intermediate variables and library calls (§3, and the
"code vs formula" discussion in ``insights.md``).

Orientation for a new reader
----------------------------
This module is the vocabulary the rest of the system speaks; read it first.
Nothing here imports anything from the package, so it is also the only module you
can read without holding the others in your head.

The lifecycle of one ``Alpha``, and which module writes which field:

    AlphaGenerator / ThinkingEvolution   ->  code, name, rationale, lineage
    QualityChecker                       ->  checks[], rejected_at, reject_reason
    FitnessEvaluator                     ->  fitness
    assign_tiers                          ->  tier
    RunArchive                            ->  reads everything, writes nothing

Two conventions worth internalising before changing anything:

* ``fitness is None`` means *never scored*, which is different from *scored badly*.
  Adaptive Generation distinguishes the two when it picks failure examples.
* ``rejected_at is not None`` means dead.  A rejected alpha is still kept and
  archived — the rejection reason is the most useful diagnostic the run produces.
"""

from __future__ import annotations

import hashlib
import re
import time
from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import Any, Dict, List, Optional


class AlphaTier(str, Enum):
    """Fitness tier assigned by :mod:`cogalpha.fitness.thresholds`."""

    INVALID = "invalid"
    """Failed the quality checker, or failed a metric's minimum bound."""

    PLAIN = "plain"
    """Executable and leakage-free, but below the qualified percentile."""

    QUALIFIED = "qualified"
    """All five metrics above the qualified percentile -> next parent pool."""

    ELITE = "elite"
    """All five metrics above the elite percentile -> final candidate pool."""


class CheckStage(str, Enum):
    """Stages of the multi-agent quality checker (§3.3, Appendix A.3)."""

    CODE_QUALITY = "code_quality"
    CODE_REPAIR = "code_repair"
    JUDGE = "judge"
    LOGIC_IMPROVEMENT = "logic_improvement"
    STATIC_AUDIT = "static_audit"
    EXECUTE = "execute"
    NUMERIC_STABILITY = "numeric_stability"
    LEAKAGE_UNIT_TEST = "leakage_unit_test"


class EvolutionOp(str, Enum):
    """How an alpha came into being."""

    SEED = "seed"
    """Hand-written seed alpha (e.g. paper Listing 1)."""

    HIERARCHY = "hierarchy"
    """Generated by a task-specific agent of the seven-level hierarchy."""

    MUTATION = "mutation"
    CROSSOVER = "crossover"
    CROSSOVER_THEN_MUTATION = "crossover_then_mutation"
    ELITISM = "elitism"
    """Carried forward unchanged from the previous generation."""


@dataclass
class Lineage:
    """Provenance of an alpha, so an evolution path can be audited.

    ``insights.md`` calls this out as a practical requirement: a quant needs to
    know which two parents a factor was recombined from before trusting it.
    """

    op: EvolutionOp = EvolutionOp.SEED
    parents: List[str] = field(default_factory=list)
    """``alpha_id`` of each parent. One entry for a mutation, two for a crossover."""

    agent: Optional[str] = None
    """Name of the hierarchy agent this descends from, or ``"crossbred"`` when a
    crossover mixed two different agents' lineages."""

    level: Optional[int] = None
    """Hierarchy level 1-7; ``None`` for a crossbred alpha whose parents disagree."""

    guidance_mode: Optional[str] = None
    generation: int = 0
    cycle: int = 0
    """Sub-cycle index. ``generation`` keeps counting across sub-cycles, so
    (generation 9, cycle 1) is unambiguous."""

    repair_rounds: int = 0
    improve_rounds: int = 0
    """How many times the Code Repair / Logic Improvement agents rewrote this alpha.
    A repaired alpha stays the *same* candidate at a later revision — see
    ``QualityChecker._adopt`` for why it is not treated as a new individual."""

    def to_dict(self) -> Dict[str, Any]:
        """JSON-safe lineage, with the Enum flattened to its value."""
        d = asdict(self)
        # asdict leaves the Enum instance in place; JSON needs its value.
        d["op"] = self.op.value
        return d


@dataclass
class Fitness:
    """The five predictive-power metrics of §3.4 plus the two backtest metrics.

    ``ic``/``rank_ic`` measure linear and monotone association with the forward
    return; ``icir``/``rank_icir`` their temporal stability; ``mi`` the
    non-linear dependence.  ``aer``/``ir`` (§B.3) are reported but not used for
    tiering, matching the paper.

    Scale note: ``mi`` is on whichever scale ``FitnessConfig.mi_scale`` selects
    (default ``corr_equivalent``, comparable to |IC|; not nats).  See
    :func:`cogalpha.fitness.metrics.mutual_information`.
    """

    ic: float = float("nan")
    icir: float = float("nan")
    rank_ic: float = float("nan")
    rank_icir: float = float("nan")
    mi: float = float("nan")

    aer: Optional[float] = None
    ir: Optional[float] = None
    """``None`` when the backtest was not run (it is off during search).
    Distinguish from ``nan``, which would mean it ran and produced nothing."""

    # --- diagnostics, not used for selection ---------------------------------
    nan_ratio: float = float("nan")
    """Missing share **of the tradable universe**, not of the wide rectangle."""

    coverage: float = float("nan")
    n_days: int = 0
    """Days that survived the ``min_names_per_day`` filter and entered the IC series.
    A small value next to a long window means most cross-sections were too thin."""

    ic_series_std: float = float("nan")

    #: Metric names that participate in tiering, in canonical order.
    #: A metric absent from this tuple is reported but does not select. Adding one
    #: here also requires an entry in both bound dicts of ``FitnessConfig``.
    TIER_METRICS = ("ic", "icir", "rank_ic", "rank_icir", "mi")

    def tier_values(self) -> Dict[str, float]:
        """The five tiering metrics as a dict, in canonical order."""
        return {m: getattr(self, m) for m in self.TIER_METRICS}

    def is_finite(self) -> bool:
        """True when all five tiering metrics are finite.

        Gate used before an alpha enters a percentile computation: one NaN would
        propagate into the cutoff and disqualify the whole generation.
        """
        vals = self.tier_values().values()
        return all(v == v and abs(v) != float("inf") for v in vals)

    def to_dict(self) -> Dict[str, Any]:
        """Plain dict for the archive. NaN survives here and is cleaned at write time."""
        return asdict(self)


@dataclass
class CheckReport:
    """Outcome of one quality-checker stage.

    Appended to ``Alpha.checks`` in pipeline order, pass or fail, so the archive
    shows how far an alpha got and not merely that it died.  ``payload`` carries
    stage-specific numbers (NaN ratios, probe diffs, import lists) for later
    analysis without re-running.
    """

    stage: CheckStage
    passed: bool
    detail: str = ""
    payload: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "stage": self.stage.value,
            "passed": self.passed,
            "detail": self.detail,
            "payload": self.payload,
        }


def _short_hash(text: str) -> str:
    """12 hex chars of SHA-1. Collision risk is negligible at run scale (~1e5 alphas)."""
    return hashlib.sha1(text.encode("utf-8")).hexdigest()[:12]


# Patterns used by canonical_code. Kept module-level so they compile once: this
# runs on every alpha_id access, which happens in inner loops.
_DEF_RE = re.compile(r"\bdef\s+([A-Za-z_]\w*)\s*\(")
_COMMENT_RE = re.compile(r"#.*$", re.MULTILINE)
_DOCSTRING_RE = re.compile(r'("""|\'\'\')(?:.|\n)*?\1')



def canonical_code(code: str, name: Optional[str] = None) -> str:
    """Normalise source so structurally identical alphas hash alike.

    Removes the things that differ between two alphas doing the same thing:

    * the function name and every self-reference to it (generated names carry a
      random suffix, so ``factor_reversal_20d_5391`` and
      ``factor_reversal_20d_7660`` are the same alpha under two labels);
    * docstrings and comments, which the LLM rewords freely;
    * whitespace.

    Needed because a name-sensitive hash makes de-duplication and the
    "unique structures" count meaningless.  Observed on a real CSI300 run: three
    candidates with byte-identical logic and identical metrics
    (IC +0.0243, RankIC +0.0361) were all admitted, and the run reported 102 of
    102 alphas as structurally unique.
    """
    if name is None:
        match = _DEF_RE.search(code)
        name = match.group(1) if match else None

    text = code
    if name:
        # Replace the identifier both as a bare name and as a string literal:
        # generated code habitually writes out['factor_x'] = ..., so missing the
        # literal would leave the random suffix in the canonical form.
        text = re.sub(rf"\b{re.escape(name)}\b", "_ALPHA_", text)
        text = text.replace(f"'{name}'", "'_ALPHA_'").replace(f'"{name}"', "'_ALPHA_'")

    text = _DOCSTRING_RE.sub("", text)
    text = _COMMENT_RE.sub("", text)
    # Collapse all whitespace: indentation and blank lines carry no logic here.
    return " ".join(text.split())


@dataclass
class Alpha:
    """One alpha candidate: source code, provenance, checks and fitness.

    The unit of work for the entire system.  See the field-ownership table in
    ``ARCHITECTURE.md`` §1 for which module writes what.

    Attributes
    ----------
    code:
        Python source defining exactly one top-level ``def``.  The function takes
        **one instrument's** date-indexed OHLCV :class:`pandas.DataFrame` and
        returns either a ``Series`` aligned to its index or the same frame with one
        added column (both shapes are accepted by :mod:`cogalpha.quality.sandbox`).
    name:
        Function name extracted from ``code``; also the factor's column name.  These
        must agree: generated code assigns to ``out[name]`` and returns that column,
        so a rename that misses the string literal raises ``KeyError`` at return
        time.  :func:`cogalpha.agents.parse.rename_function` handles both.
    rationale:
        Natural-language explanation the generating agent attached, taken from the
        docstring.  The paper treats this as the interpretability payload (§4.4).
    meta:
        Free-form scratch space: sampling temperature, operator name, evaluation
        seconds, backtest dict.  Nothing here is load-bearing — read it for
        diagnostics, do not branch on it.
    """

    code: str
    name: str
    rationale: str = ""
    lineage: Lineage = field(default_factory=Lineage)
    fitness: Optional[Fitness] = None
    tier: AlphaTier = AlphaTier.INVALID
    """Starts INVALID and is only promoted by ``assign_tiers``. An alpha that never
    reaches tiering therefore reads INVALID, which is the honest default."""

    checks: List[CheckReport] = field(default_factory=list)
    rejected_at: Optional[CheckStage] = None
    reject_reason: str = ""
    created_at: float = field(default_factory=time.time)
    meta: Dict[str, Any] = field(default_factory=dict)

    @property
    def alpha_id(self) -> str:
        """Content-addressed id, insensitive to naming and prose.

        The hash is over :func:`canonical_code`, not the raw source, so the id
        identifies the alpha's *logic*.  Two candidates that differ only in their
        randomly-suffixed function name or a reworded docstring collapse to one
        entry -- which is what makes de-duplication and the "unique structures"
        count mean something rather than always equal the number generated.

        Recomputed on every access (no caching) because ``code`` is mutable: a
        repair or improvement round rewrites it, and a cached id would then point at
        the pre-repair logic.
        """
        return f"alpha-{_short_hash(canonical_code(self.code, self.name))}"

    @property
    def display_id(self) -> str:
        """``name-hash``, for logs and filenames where the name aids reading.

        Never use this as a dict key -- two spellings of the same logic produce two
        different ``display_id`` values but one ``alpha_id``.
        """
        return f"{self.name}-{_short_hash(canonical_code(self.code, self.name))}"

    @property
    def is_valid(self) -> bool:
        """Survived the checker *and* was promoted to at least PLAIN by tiering."""
        return self.rejected_at is None and self.tier is not AlphaTier.INVALID

    def add_check(self, report: CheckReport) -> None:
        """Append a stage outcome. Called for passes as well as failures."""
        self.checks.append(report)

    def reject(self, stage: CheckStage, reason: str) -> None:
        """Mark the alpha dead at ``stage``.

        Terminal: nothing downstream re-examines a rejected alpha, but it is still
        archived, and Adaptive Generation feeds its reason back into the next
        generation's prompt.
        """
        self.rejected_at = stage
        self.reject_reason = reason
        self.tier = AlphaTier.INVALID

    def to_dict(self) -> Dict[str, Any]:
        """Full record for ``alphas.jsonl``, including the source and every check."""
        return {
            "alpha_id": self.alpha_id,
            "display_id": self.display_id,
            "name": self.name,
            "code": self.code,
            "rationale": self.rationale,
            "lineage": self.lineage.to_dict(),
            "fitness": self.fitness.to_dict() if self.fitness else None,
            "tier": self.tier.value,
            "checks": [c.to_dict() for c in self.checks],
            "rejected_at": self.rejected_at.value if self.rejected_at else None,
            "reject_reason": self.reject_reason,
            "created_at": self.created_at,
            "meta": self.meta,
        }


@dataclass
class GenerationRecord:
    """Per-generation bookkeeping, written to the run archive.

    Kept deliberately rich: the ablation table (§4.3) and the threshold
    sensitivity study (§4.7) are both re-derivable from a sequence of these
    without re-running the search.

    ``op_counts`` is tallied *after* de-duplication, so it says what each operator
    contributed rather than what it emitted; the difference appears as the
    ``duplicates_dropped`` key.  ``operator_failures`` and ``injected`` also live in
    that dict rather than as separate fields, so a new operator needs no schema
    change.
    """

    generation: int
    cycle: int
    agent: str
    op_counts: Dict[str, int] = field(default_factory=dict)
    n_generated: int = 0
    n_passed_checker: int = 0
    n_qualified: int = 0
    n_elite: int = 0

    reject_counts: Dict[str, int] = field(default_factory=dict)
    best: Dict[str, Any] = field(default_factory=dict)
    percentile_cutoffs: Dict[str, float] = field(default_factory=dict)
    elite_mean_score: float = float("nan")
    llm_calls: int = 0
    wall_seconds: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)
