"""Proposal experts: turn a StructuredAction into candidate Programs.

The meta-controller (strategy) decides *what* to try; experts decide *how*
to write the code. Two candidate families are provided:

- ``GBDTExpert``: deterministic mutation of a LightGBM config embedded in a
  candidate template. No LLM needed — this is the high-throughput,
  low-variance explorer.
- ``NNExpert``: LLM-guided edits to an NN candidate template (MLP /
  temporal transformer blocks). This is the high-variance family added to
  fix the selection-pressure bottleneck measured in exp1 (GBDT-only pools
  have sd_noise too low for selection to bite).

Both emit code that conforms to the *candidate contract*: a self-contained
program reading ``--split-config`` JSON and printing a JSON result line
``FAMOU_RESULT {...}`` with metrics. The F1/F2 evaluator and the sealed
gate both execute this contract; only the split they point at differs.
"""

from __future__ import annotations

import json
import uuid
from typing import Any, Dict, List, Optional, Sequence

from famou.core.data import Program
from famou.core.types import Language
from famou.reliability.types import (
    CandidatePackage,
    ExpertKind,
    QuantModelSpec,
    StructuredAction,
)
from famou.utils.id_gen import get_timestamp


# =============================================================================
# Candidate contract template
# =============================================================================
#
# The generated program is a self-contained trainer. It must:
#   1. parse --split-config <json path> with keys:
#        {train_start, train_end, dev_start, dev_end, embargo_days,
#         seed_list, fidelity, max_boost_rounds}
#   2. train on [train_start, train_end] only (preprocessing fit there too)
#   3. evaluate on [dev_start, dev_end] (the *visible* dev — which calendar
#      slice that is depends on who invokes it: F1/F2 evaluator points it at
#      visible_dev, the sealed gate points it at sealed_promotion)
#   4. print exactly one line: FAMOU_RESULT {"rank_ic": ..., "icir": ..., ...}
#
# Keeping the candidate agnostic about *which* split it evaluates is what
# lets the same frozen code run under both visible and sealed protocols.

CANDIDATE_TEMPLATE = '''"""EvoQuant candidate — {family} (generated by {expert}).

Contract: reads --split-config JSON, trains on train range, evaluates on
dev range, prints one `FAMOU_RESULT {{...}}` line with daily RankIC stats.
"""

import argparse
import json
import math


HYPERPARAMS = {hyperparams_json}


def load_split_config(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def train_and_predict(split_cfg, params, seed):
    """Train on split_cfg train range, return per-day predictions on dev.

    Returns a dict {{"date": [str], "pred": [float], "label": [float]}}.
    Data loading is delegated to the shared runner injected by the harness
    (qlib Alpha158 features, CSZScoreNorm label, embargo applied by the
    harness when it builds the split config).
    """
    from famou_candidate_runtime import run_candidate  # provided by evaluator env

    return run_candidate(split_cfg, params, seed, family="{family}")


def daily_rank_ic(result):
    from scipy.stats import rankdata
    import numpy as np

    by_date = {{}}
    for d, p, y in zip(result["date"], result["pred"], result["label"]):
        by_date.setdefault(d, []).append((p, y))
    ics = []
    for d, pairs in sorted(by_date.items()):
        if len(pairs) < 3:
            continue
        p = np.array([a for a, _ in pairs])
        y = np.array([b for _, b in pairs])
        if p.std() == 0 or y.std() == 0:
            continue
        ics.append(float(np.corrcoef(rankdata(p), rankdata(y))[0, 1]))
    return ics


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--split-config", required=True)
    cfg = load_split_config(ap.parse_args().split_config)

    all_ics = []
    per_seed_mean = []
    per_seed_icir = []
    for seed in cfg.get("seed_list", [11]):
        res = train_and_predict(cfg, HYPERPARAMS, seed)
        ics = daily_rank_ic(res)
        if ics:
            m = sum(ics) / len(ics)
            # ICIR is a time-series ratio: mean(daily IC) / std(daily IC)
            # WITHIN this seed. Never across seeds.
            s = math.sqrt(sum((v - m) ** 2 for v in ics) / max(1, len(ics) - 1))
            per_seed_mean.append(m)
            per_seed_icir.append((m / s) if s > 0 else 0.0)
            all_ics.extend(ics)

    if not all_ics:
        print('FAMOU_RESULT {{"validity": 0.0, "error_info": "no valid IC days"}}')
        return

    mean_ic = sum(all_ics) / len(all_ics)
    std_ic = math.sqrt(sum((v - mean_ic) ** 2 for v in all_ics) / max(1, len(all_ics) - 1))
    out = {{
        "validity": 1.0,
        "combined_score": mean_ic,
        "rank_ic": mean_ic,
        "rank_ic_std": std_ic,
        "icir": (mean_ic / std_ic) if std_ic > 0 else 0.0,
        "per_seed_rank_ic": per_seed_mean,
        "per_seed_icir": per_seed_icir,
        "n_ic_days": len(all_ics),
    }}
    print("FAMOU_RESULT " + json.dumps(out))


if __name__ == "__main__":
    main()
'''


FORMULA_TEMPLATE = '''"""EvoQuant candidate — factor formula (generated by {expert}).

A DETERMINISTIC multi-factor score: no model is fitted, so there is no seed
randomness and no training cost. Evidence strength comes from stability across
subperiods rather than across seeds.

Contract: identical to the model candidates — reads --split-config, prints one
`FAMOU_RESULT {{...}}` line — so formula and model candidates compete in the
same pool under the same protocol.
"""

import argparse
import json
import math


HYPERPARAMS = {hyperparams_json}


def load_split_config(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def score_universe(split_cfg, params):
    """Weighted combination of cross-sectionally normalised Alpha158 factors.

    The normalisation is applied by the shared runner so every formula uses the
    same convention: raw factor scales differ by orders of magnitude, and an
    un-normalised weighted sum would be decided by whichever column is largest
    rather than by the weights.
    """
    from famou_candidate_runtime import combine_factors  # provided by evaluator env

    return combine_factors(split_cfg, params["terms"])


def daily_rank_ic(result):
    from scipy.stats import rankdata
    import numpy as np

    by_date = {{}}
    for d, p, y in zip(result["date"], result["pred"], result["label"]):
        by_date.setdefault(d, []).append((p, y))
    ics = []
    for d, pairs in sorted(by_date.items()):
        if len(pairs) < 3:
            continue
        p = np.array([a for a, _ in pairs])
        y = np.array([b for _, b in pairs])
        if p.std() == 0 or y.std() == 0:
            continue
        ics.append(float(np.corrcoef(rankdata(p), rankdata(y))[0, 1]))
    return ics


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--split-config", required=True)
    cfg = load_split_config(ap.parse_args().split_config)

    res = score_universe(cfg, HYPERPARAMS)
    ics = daily_rank_ic(res)
    if not ics:
        print('FAMOU_RESULT {{"validity": 0.0, "error_info": "no valid IC days"}}')
        return

    mean_ic = sum(ics) / len(ics)
    std_ic = math.sqrt(sum((v - mean_ic) ** 2 for v in ics) / max(1, len(ics) - 1))
    icir = (mean_ic / std_ic) if std_ic > 0 else 0.0
    out = {{
        "validity": 1.0,
        "combined_score": mean_ic,
        "rank_ic": mean_ic,
        "rank_ic_std": std_ic,
        "icir": icir,
        # One element on purpose: the candidate is deterministic, so a second
        # "seed" would be the identical number. Stability lives in subperiods.
        "per_seed_rank_ic": [mean_ic],
        "per_seed_icir": [icir],
        "subperiod_rank_ic": res.get("subperiod_rank_ic", []),
        "deterministic": True,
        "n_ic_days": len(ics),
        "factors_used": res.get("factors_used", []),
    }}
    print("FAMOU_RESULT " + json.dumps(out))


if __name__ == "__main__":
    main()
'''


def _render_hyperparams(hyperparams: Dict[str, Any]) -> str:
    """Render HYPERPARAMS as a PYTHON literal, one key per line.

    Not ``json.dumps``: JSON writes ``true``/``false``/``null``, which are
    NameErrors in Python. That only bites families with boolean or None
    hyperparameters (the NN families have ``layer_norm``), so a JSON-rendered
    template passes the GBDT tests and then fails every MLP candidate at
    import time.
    """
    lines = [f"    {key!r}: {value!r}," for key, value in hyperparams.items()]
    return "{\n" + "\n".join(lines) + "\n}"


def _render_template(family: str, expert: str, hyperparams: Dict[str, Any]) -> str:
    return CANDIDATE_TEMPLATE.format(
        family=family,
        expert=expert,
        hyperparams_json=_render_hyperparams(hyperparams),
    )


# =============================================================================
# Base expert
# =============================================================================


class ProposalExpert:
    """Base class for action -> candidate translation."""

    kind: ExpertKind = ExpertKind.EXPLORE
    model_family: str = "unknown"

    def propose(
        self,
        action: StructuredAction,
        parents: List[Program],
        *,
        iteration: int,
    ) -> Program:
        raise NotImplementedError

    # -- packaging ------------------------------------------------------

    def build_spec(self, hyperparams: Dict[str, Any]) -> QuantModelSpec:
        """Structured view of the candidate.

        Subclasses split their hyperparameter dict into the four editable
        components so ``edit_target`` can name one and a diff can show which
        one actually moved.
        """
        return QuantModelSpec(
            model_family=self.model_family, architecture=dict(hyperparams)
        )

    def package(
        self,
        program: Program,
        *,
        episode_id: str,
        data_contract_hash: str = "",
        task_spec_hash: str = "",
    ) -> CandidatePackage:
        """Wrap a generated Program as a fully-stamped CandidatePackage.

        The two hashes travel with the candidate so a result can never be
        compared against a protocol it was not produced under.
        """
        try:
            hyperparams = self.extract_hyperparams(program)
        except (ValueError, SyntaxError):
            hyperparams = {}
        meta = program.meta or {}
        return CandidatePackage(
            candidate_id=program.id,
            episode_id=episode_id,
            code=program.code,
            code_hash=CandidatePackage.hash_code(program.code),
            spec=self.build_spec(hyperparams),
            parent_ids=list(meta.get("parent_ids", [])),
            decision_id=meta.get("decision_id"),
            expert=meta.get("expert", self.kind.value),
            data_contract_hash=data_contract_hash,
            task_spec_hash=task_spec_hash,
            generation_meta={
                "edit_target": meta.get("edit_target"),
                "fidelity": meta.get("fidelity"),
                "seed_list": meta.get("seed_list", []),
                "rationale": meta.get("rationale", ""),
                "llm_guided": bool(meta.get("llm_guided", False)),
            },
        )

    # -- helpers --------------------------------------------------------

    def _new_program(
        self,
        code: str,
        *,
        action: StructuredAction,
        parents: List[Program],
        iteration: int,
    ) -> Program:
        parent_id = parents[0].id if parents else None
        generation = (parents[0].generation + 1) if parents else 0
        return Program(
            id=f"cand_{iteration}_{uuid.uuid4().hex[:8]}",
            code=code,
            generation=generation,
            iteration=iteration,
            language=Language.PYTHON,
            parent_id=parent_id,
            created_at=get_timestamp(),
            meta={
                "expert": self.kind.value,
                "model_family": self.model_family,
                "edit_target": action.edit_target,
                "fidelity": int(action.fidelity.value),
                "seed_list": list(action.seed_list),
                "parent_ids": [p.id for p in parents],
                "rationale": action.rationale,
            },
        )

    @staticmethod
    def extract_hyperparams(program: Program) -> Dict[str, Any]:
        """Pull the HYPERPARAMS dict out of a candidate's source code."""
        import ast

        tree = ast.parse(program.code)
        for node in tree.body:
            if isinstance(node, ast.Assign):
                for target in node.targets:
                    if isinstance(target, ast.Name) and target.id == "HYPERPARAMS":
                        try:
                            return ast.literal_eval(node.value)
                        except (ValueError, TypeError):
                            # HYPERPARAMS built with expressions (e.g. 2 ** 8),
                            # or JSON-style literals in a hand-written /
                            # LLM-authored candidate: evaluate the restricted
                            # expression instead. Our own templates emit Python
                            # literals (see _render_hyperparams), so this path
                            # only serves foreign candidates.
                            safe_globals = {
                                "__builtins__": {},
                                "true": True, "false": False, "null": None,
                                "True": True, "False": False, "None": None,
                            }
                            return eval(  # noqa: S307 - candidate-internal constants only
                                compile(ast.Expression(node.value), "<hp>", "eval"),
                                safe_globals,
                                {},
                            )
        raise ValueError(f"No HYPERPARAMS assignment found in {program.id}")


# =============================================================================
# GBDT expert (deterministic, no LLM)
# =============================================================================

DEFAULT_GBDT: Dict[str, Any] = {
    "objective": "mse",
    "learning_rate": 0.08,
    "num_leaves": 128,
    "max_depth": 8,
    "colsample_bytree": 0.8,
    "subsample": 0.8,
    "lambda_l1": 100.0,
    "lambda_l2": 500.0,
    "min_data_in_leaf": 50,
    "bagging_freq": 1,
}


class GBDTExpert(ProposalExpert):
    """Deterministic LightGBM config mutation (matches exp2's `mutate` scales).

    Used for explore/mutate/local_hpo actions on the gbdt family. Same
    log-normal perturbation scales as the frozen exp2 pipeline so results
    stay comparable with the measured noise floor.
    """

    model_family = "gbdt"

    #: which hyperparameters belong to which QuantModelSpec component
    _OPTIMIZER_KEYS = {"learning_rate", "lambda_l1", "lambda_l2"}
    _TRAINING_KEYS = {"subsample", "bagging_freq", "min_data_in_leaf"}
    _FEATURE_KEYS = {"colsample_bytree"}

    def build_spec(self, hyperparams: Dict[str, Any]) -> QuantModelSpec:
        hp = dict(hyperparams)
        return QuantModelSpec(
            model_family=self.model_family,
            feature_pipeline={k: hp[k] for k in self._FEATURE_KEYS if k in hp},
            architecture={
                k: v
                for k, v in hp.items()
                if k not in self._OPTIMIZER_KEYS
                and k not in self._TRAINING_KEYS
                and k not in self._FEATURE_KEYS
                and k != "objective"
            },
            loss=str(hp.get("objective", "mse")),
            optimizer={k: hp[k] for k in self._OPTIMIZER_KEYS if k in hp},
            training={k: hp[k] for k in self._TRAINING_KEYS if k in hp},
        )

    def __init__(self, kind: ExpertKind = ExpertKind.MUTATE, rng_seed: int = 0):
        self.kind = kind
        import random

        self._rng = random.Random(rng_seed)

    def propose(
        self,
        action: StructuredAction,
        parents: List[Program],
        *,
        iteration: int,
    ) -> Program:
        base = DEFAULT_GBDT
        if parents:
            try:
                base = self.extract_hyperparams(parents[0])
            except (ValueError, SyntaxError):
                base = dict(DEFAULT_GBDT)

        params = dict(base)
        if self.kind in (ExpertKind.MUTATE, ExpertKind.LOCAL_HPO, ExpertKind.EXPLORE):
            params = self._mutate(params)
        code = _render_template(self.model_family, self.kind.value, params)
        return self._new_program(code, action=action, parents=parents, iteration=iteration)

    def _mutate(self, p: Dict[str, Any]) -> Dict[str, Any]:
        import math

        rng = self._rng
        out = dict(p)
        def lognormal(x, sigma):
            return x * math.exp(rng.gauss(0, sigma))

        out["learning_rate"] = min(0.4, max(0.05, lognormal(float(p["learning_rate"]), 0.20)))
        out["num_leaves"] = int(min(512, max(32, lognormal(float(p["num_leaves"]), 0.25))))
        out["max_depth"] = int(min(12, max(4, p["max_depth"] + rng.randint(-2, 2))))
        out["colsample_bytree"] = min(1.0, max(0.5, p["colsample_bytree"] + rng.gauss(0, 0.06)))
        out["subsample"] = min(1.0, max(0.5, p["subsample"] + rng.gauss(0, 0.06)))
        out["lambda_l1"] = min(800.0, max(20.0, lognormal(float(p["lambda_l1"]), 0.30)))
        out["lambda_l2"] = min(2000.0, max(50.0, lognormal(float(p["lambda_l2"]), 0.30)))
        out["min_data_in_leaf"] = int(min(200, max(5, lognormal(float(p["min_data_in_leaf"]), 0.4))))
        return out


# =============================================================================
# NN expert (LLM-guided, high-variance family)
# =============================================================================

DEFAULT_MLP: Dict[str, Any] = {
    "hidden_dims": [256, 128],
    "dropout": 0.1,
    "learning_rate": 0.001,
    "weight_decay": 0.0001,
    "batch_size": 512,
    "epochs": 20,
    "early_stopping": 5,
    "layer_norm": True,
}


class NNExpert(ProposalExpert):
    """Neural candidate proposer (MLP / temporal blocks).

    Two modes:
    - deterministic config mutation (no LLM, for tests / cheap explore)
    - LLM-guided edit: subclasses or the strategy layer inject
      ``llm_edit_fn(parent_code, action, context_summary) -> new_code``.
      This is the primary path in production; kept as an injectable callable
      so the expert itself stays unit-testable without an LLM.
    """

    model_family = "mlp"

    _OPTIMIZER_KEYS = {"learning_rate", "weight_decay"}
    _TRAINING_KEYS = {"batch_size", "epochs", "early_stopping"}

    def build_spec(self, hyperparams: Dict[str, Any]) -> QuantModelSpec:
        hp = dict(hyperparams)
        return QuantModelSpec(
            model_family=self.model_family,
            feature_pipeline={},
            architecture={
                k: v
                for k, v in hp.items()
                if k not in self._OPTIMIZER_KEYS and k not in self._TRAINING_KEYS
            },
            loss=str(hp.get("loss", "mse")),
            optimizer={k: hp[k] for k in self._OPTIMIZER_KEYS if k in hp},
            training={k: hp[k] for k in self._TRAINING_KEYS if k in hp},
        )

    def __init__(
        self,
        kind: ExpertKind = ExpertKind.EXPLORE,
        rng_seed: int = 0,
        llm_edit_fn: Optional[Any] = None,
        family: str = "mlp",
    ):
        self.kind = kind
        self.model_family = family
        self._llm_edit_fn = llm_edit_fn
        import random

        self._rng = random.Random(rng_seed)

    def propose(
        self,
        action: StructuredAction,
        parents: List[Program],
        *,
        iteration: int,
    ) -> Program:
        if self._llm_edit_fn is not None and parents:
            code = self._llm_edit_fn(parents[0].code, action)
            program = self._new_program(
                code, action=action, parents=parents, iteration=iteration
            )
            program.meta["llm_guided"] = True
            return program

        base = DEFAULT_MLP
        if parents:
            try:
                base = self.extract_hyperparams(parents[0])
            except (ValueError, SyntaxError):
                base = dict(DEFAULT_MLP)
        params = self._mutate(base)
        code = _render_template(self.model_family, self.kind.value, params)
        return self._new_program(code, action=action, parents=parents, iteration=iteration)

    def _mutate(self, p: Dict[str, Any]) -> Dict[str, Any]:
        rng = self._rng
        out = dict(p)
        dims = list(out.get("hidden_dims", [256, 128]))
        # Randomly grow/shrink/shift one layer
        op = rng.choice(["grow", "shrink", "rescale", "toggle_ln"])
        if op == "grow" and len(dims) < 4:
            dims.append(max(32, dims[-1] // 2))
        elif op == "shrink" and len(dims) > 1:
            dims.pop()
        elif op == "rescale":
            idx = rng.randrange(len(dims))
            dims[idx] = int(min(1024, max(32, dims[idx] * rng.choice([0.5, 2.0]))))
        elif op == "toggle_ln":
            out["layer_norm"] = not out.get("layer_norm", True)
        out["hidden_dims"] = dims
        out["dropout"] = min(0.5, max(0.0, out["dropout"] + rng.gauss(0, 0.05)))
        out["learning_rate"] = min(0.01, max(1e-4, out["learning_rate"] * (2 ** rng.gauss(0, 0.5))))
        out["epochs"] = int(min(60, max(5, out["epochs"] + rng.randint(-5, 10))))
        return out


# =============================================================================
# Formula expert (deterministic, no training)
# =============================================================================

#: Alpha158 factor families worth combining, grouped by what they measure.
#: Sampling across groups rather than uniformly over all 158 columns keeps a
#: formula from being five flavours of the same momentum signal — the diversity
#: that makes a multi-factor score worth more than its best single term.
FACTOR_GROUPS: Dict[str, List[str]] = {
    "momentum": ["ROC5", "ROC10", "ROC20", "ROC60", "MA5", "MA20", "MA60"],
    "reversal": ["RSV5", "RSV20", "RANK5", "RANK20", "QTLU20", "QTLD20"],
    "volatility": ["STD5", "STD20", "STD60", "MAX20", "MIN20", "BETA20"],
    "trend_quality": ["RSQR5", "RSQR20", "RSQR60", "RESI5", "RESI20"],
    "volume": ["VMA5", "VMA20", "VSTD20", "WVMA20", "VSUMP20", "VSUMD20"],
    "price_volume": ["CORR5", "CORR20", "CORD5", "CORD20"],
    "updown": ["CNTP20", "CNTN20", "CNTD20", "SUMP20", "SUMN20", "SUMD20"],
    "shape": ["KMID", "KLEN", "KUP", "KLOW", "KSFT"],
    "position": ["IMAX20", "IMIN20", "IMXD20"],
}

TRANSFORMS = ("zscore", "rank", "sign")


class FormulaExpert(ProposalExpert):
    """Proposes deterministic multi-factor scores over Alpha158.

    Why this family exists alongside the trained models: a formula costs
    ~0.06s to score against ~40-105s to train one. That two-orders-of-magnitude
    gap is what makes the budget machinery (per-candidate compute ceilings,
    cost penalties in the reward, the fidelity ladder) do real work — with only
    GBDT and MLP in the pool, every candidate costs roughly the same and those
    mechanisms are never exercised.

    It is also the interpretable end of the pool: the winning candidate is a
    weighted factor list you can print in a paper, not a boosted ensemble.
    """

    model_family = "formula"

    def __init__(
        self,
        kind: ExpertKind = ExpertKind.MUTATE,
        rng_seed: int = 0,
        *,
        min_terms: int = 3,
        max_terms: int = 8,
        llm_edit_fn: Optional[Any] = None,
    ):
        self.kind = kind
        self.min_terms = min_terms
        self.max_terms = max_terms
        self._llm_edit_fn = llm_edit_fn
        import random

        self._rng = random.Random(rng_seed)

    # -- spec ------------------------------------------------------------

    def build_spec(self, hyperparams: Dict[str, Any]) -> QuantModelSpec:
        terms = hyperparams.get("terms", [])
        return QuantModelSpec(
            model_family=self.model_family,
            # For a formula, the "feature pipeline" IS the model: which factors
            # and how they are normalised.
            feature_pipeline={
                "factors": [t.get("feature") for t in terms],
                "transforms": [t.get("transform") for t in terms],
            },
            architecture={"n_terms": len(terms), "kind": "linear_combination"},
            loss="none",
            optimizer={},
            training={"deterministic": True, "fitted_parameters": 0},
        )

    # -- proposal --------------------------------------------------------

    def propose(
        self,
        action: StructuredAction,
        parents: List[Program],
        *,
        iteration: int,
    ) -> Program:
        if self._llm_edit_fn is not None and parents:
            code = self._llm_edit_fn(parents[0].code, action)
            program = self._new_program(code, action=action, parents=parents,
                                        iteration=iteration)
            program.meta["llm_guided"] = True
            return program

        base: Optional[Dict[str, Any]] = None
        if parents and self.kind != ExpertKind.EXPLORE:
            try:
                base = self.extract_hyperparams(parents[0])
            except (ValueError, SyntaxError):
                base = None

        params = self._fresh() if base is None else self._mutate(base)
        code = _render_formula(self.kind.value, params)
        return self._new_program(code, action=action, parents=parents,
                                 iteration=iteration)

    # -- generation ------------------------------------------------------

    def _fresh(self) -> Dict[str, Any]:
        """Sample a new formula: one factor from each of K distinct groups."""
        rng = self._rng
        n = rng.randint(self.min_terms, self.max_terms)
        groups = rng.sample(list(FACTOR_GROUPS), min(n, len(FACTOR_GROUPS)))
        terms = []
        for group in groups:
            terms.append({
                "feature": rng.choice(FACTOR_GROUPS[group]),
                "weight": round(rng.uniform(-1.0, 1.0), 4),
                "transform": rng.choice(TRANSFORMS),
            })
        return {"terms": self._normalise(terms)}

    def _mutate(self, base: Dict[str, Any]) -> Dict[str, Any]:
        rng = self._rng
        terms = [dict(t) for t in base.get("terms", [])]
        if not terms:
            return self._fresh()

        op = rng.choice(["reweight", "swap", "add", "drop", "retransform"])
        if op == "reweight":
            # Perturb every weight; large edits to one term tend to just delete
            # it, which the `drop` op already covers.
            for t in terms:
                t["weight"] = round(float(t["weight"]) + rng.gauss(0, 0.25), 4)
        elif op == "swap" and terms:
            t = rng.choice(terms)
            group = self._group_of(t["feature"]) or rng.choice(list(FACTOR_GROUPS))
            t["feature"] = rng.choice(FACTOR_GROUPS[group])
        elif op == "add" and len(terms) < self.max_terms:
            used_groups = {self._group_of(t["feature"]) for t in terms}
            spare = [g for g in FACTOR_GROUPS if g not in used_groups]
            group = rng.choice(spare or list(FACTOR_GROUPS))
            terms.append({
                "feature": rng.choice(FACTOR_GROUPS[group]),
                "weight": round(rng.uniform(-0.6, 0.6), 4),
                "transform": rng.choice(TRANSFORMS),
            })
        elif op == "drop" and len(terms) > self.min_terms:
            terms.pop(rng.randrange(len(terms)))
        elif op == "retransform" and terms:
            rng.choice(terms)["transform"] = rng.choice(TRANSFORMS)
        return {"terms": self._normalise(terms)}

    # -- helpers ---------------------------------------------------------

    @staticmethod
    def _group_of(feature: str) -> Optional[str]:
        for group, members in FACTOR_GROUPS.items():
            if feature in members:
                return group
        return None

    @staticmethod
    def _normalise(terms: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Scale weights to unit L1, and drop terms that rounded to nothing.

        RankIC is invariant to a positive rescaling of the score, so the
        overall magnitude is not a real degree of freedom. Fixing it keeps
        mutation operating on the *relative* weights, and stops two identical
        formulas at different scales from looking like distinct candidates.
        """
        kept = [t for t in terms if abs(float(t.get("weight", 0.0))) >= 0.01]
        if not kept:
            kept = terms[:1] or [{"feature": "ROC20", "weight": 1.0,
                                  "transform": "zscore"}]
        total = sum(abs(float(t["weight"])) for t in kept) or 1.0
        for t in kept:
            t["weight"] = round(float(t["weight"]) / total, 4)
        return kept


def _render_formula(expert: str, hyperparams: Dict[str, Any]) -> str:
    return FORMULA_TEMPLATE.format(
        expert=expert,
        hyperparams_json=_render_hyperparams(hyperparams),
    )


# =============================================================================
# Registry
# =============================================================================


def default_expert_registry(
    *,
    rng_seed: int = 0,
    families: Optional[Sequence[str]] = None,
    llm_edit_fn: Optional[Any] = None,
) -> Dict[str, ProposalExpert]:
    """Experts keyed by the lookup the strategy uses: ``family`` /
    ``family_explore`` / ``family_hpo``.

    ``families`` restricts the pool — pass ``TaskSpec.allowed_model_families``
    so the search space the experts can reach is exactly the one the frozen
    contract declares. Omit it to get every implemented family.
    """
    allowed = set(families) if families else None

    def wanted(family: str) -> bool:
        return allowed is None or family in allowed

    registry: Dict[str, ProposalExpert] = {}
    if wanted("gbdt"):
        registry.update({
            "gbdt": GBDTExpert(ExpertKind.MUTATE, rng_seed=rng_seed),
            "gbdt_explore": GBDTExpert(ExpertKind.EXPLORE, rng_seed=rng_seed + 1),
            "gbdt_hpo": GBDTExpert(ExpertKind.LOCAL_HPO, rng_seed=rng_seed + 2),
        })
    if wanted("mlp"):
        registry["mlp"] = NNExpert(ExpertKind.EXPLORE, rng_seed=rng_seed + 3,
                                   family="mlp", llm_edit_fn=llm_edit_fn)
    if wanted("temporal_transformer"):
        registry["temporal_transformer"] = NNExpert(
            ExpertKind.EXPLORE, rng_seed=rng_seed + 4,
            family="temporal_transformer", llm_edit_fn=llm_edit_fn)
    if wanted("formula"):
        registry.update({
            "formula": FormulaExpert(ExpertKind.MUTATE, rng_seed=rng_seed + 5,
                                     llm_edit_fn=llm_edit_fn),
            "formula_explore": FormulaExpert(ExpertKind.EXPLORE,
                                             rng_seed=rng_seed + 6),
            "formula_hpo": FormulaExpert(ExpertKind.LOCAL_HPO,
                                         rng_seed=rng_seed + 7),
        })

    if not registry:
        raise ValueError(
            f"no experts for families={sorted(allowed or [])}; "
            "implemented: gbdt, mlp, temporal_transformer, formula"
        )
    return registry
