"""Proposal experts: turn a StructuredAction into candidate Programs.

The meta-controller (strategy) decides *what* to try; experts decide *how*
to write the code. Two candidate families are provided:

- ``GBDTExpert``: deterministic mutation of a LightGBM config embedded in a
  candidate template. No LLM needed — this is the high-throughput,
  low-variance explorer.
- ``NNExpert``: LLM-guided edits to an NN candidate template (MLP /
  temporal transformer blocks). This is the high-variance family added to
  fix the selection-pressure bottleneck measured in exp1 (GBDT-only pools
  have sd_noise too low for selection to bite).

Both emit code that conforms to the *candidate contract*: a self-contained
program reading ``--split-config`` JSON and printing a JSON result line
``FAMOU_RESULT {...}`` with metrics. The F1/F2 evaluator and the sealed
gate both execute this contract; only the split they point at differs.
"""

from __future__ import annotations

import json
import uuid
from typing import Any, Dict, List, Optional

from famou.core.data import Program
from famou.core.types import Language
from famou.reliability.types import ExpertKind, StructuredAction
from famou.utils.id_gen import get_timestamp


# =============================================================================
# Candidate contract template
# =============================================================================
#
# The generated program is a self-contained trainer. It must:
#   1. parse --split-config <json path> with keys:
#        {train_start, train_end, dev_start, dev_end, embargo_days,
#         seed_list, fidelity, max_boost_rounds}
#   2. train on [train_start, train_end] only (preprocessing fit there too)
#   3. evaluate on [dev_start, dev_end] (the *visible* dev — which calendar
#      slice that is depends on who invokes it: F1/F2 evaluator points it at
#      visible_dev, the sealed gate points it at sealed_promotion)
#   4. print exactly one line: FAMOU_RESULT {"rank_ic": ..., "icir": ..., ...}
#
# Keeping the candidate agnostic about *which* split it evaluates is what
# lets the same frozen code run under both visible and sealed protocols.

CANDIDATE_TEMPLATE = '''"""EvoQuant candidate — {family} (generated by {expert}).

Contract: reads --split-config JSON, trains on train range, evaluates on
dev range, prints one `FAMOU_RESULT {{...}}` line with daily RankIC stats.
"""

import argparse
import json
import math


HYPERPARAMS = {hyperparams_json}


def load_split_config(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def train_and_predict(split_cfg, params, seed):
    """Train on split_cfg train range, return per-day predictions on dev.

    Returns a dict {{"date": [str], "pred": [float], "label": [float]}}.
    Data loading is delegated to the shared runner injected by the harness
    (qlib Alpha158 features, CSZScoreNorm label, embargo applied by the
    harness when it builds the split config).
    """
    from famou_candidate_runtime import run_candidate  # provided by evaluator env

    return run_candidate(split_cfg, params, seed, family="{family}")


def daily_rank_ic(result):
    from scipy.stats import rankdata
    import numpy as np

    by_date = {{}}
    for d, p, y in zip(result["date"], result["pred"], result["label"]):
        by_date.setdefault(d, []).append((p, y))
    ics = []
    for d, pairs in sorted(by_date.items()):
        if len(pairs) < 3:
            continue
        p = np.array([a for a, _ in pairs])
        y = np.array([b for _, b in pairs])
        if p.std() == 0 or y.std() == 0:
            continue
        ics.append(float(np.corrcoef(rankdata(p), rankdata(y))[0, 1]))
    return ics


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--split-config", required=True)
    cfg = load_split_config(ap.parse_args().split_config)

    all_ics = []
    per_seed_mean = []
    for seed in cfg.get("seed_list", [11]):
        res = train_and_predict(cfg, HYPERPARAMS, seed)
        ics = daily_rank_ic(res)
        if ics:
            per_seed_mean.append(sum(ics) / len(ics))
            all_ics.extend(ics)

    if not all_ics:
        print('FAMOU_RESULT {{"validity": 0.0, "error_info": "no valid IC days"}}')
        return

    mean_ic = sum(all_ics) / len(all_ics)
    std_ic = math.sqrt(sum((v - mean_ic) ** 2 for v in all_ics) / max(1, len(all_ics) - 1))
    out = {{
        "validity": 1.0,
        "combined_score": mean_ic,
        "rank_ic": mean_ic,
        "rank_ic_std": std_ic,
        "icir": (mean_ic / std_ic) if std_ic > 0 else 0.0,
        "per_seed_rank_ic": per_seed_mean,
        "n_ic_days": len(all_ics),
    }}
    print("FAMOU_RESULT " + json.dumps(out))


if __name__ == "__main__":
    main()
'''


def _render_template(family: str, expert: str, hyperparams: Dict[str, Any]) -> str:
    return CANDIDATE_TEMPLATE.format(
        family=family,
        expert=expert,
        hyperparams_json=json.dumps(hyperparams, indent=4),
    )


# =============================================================================
# Base expert
# =============================================================================


class ProposalExpert:
    """Base class for action -> candidate translation."""

    kind: ExpertKind = ExpertKind.EXPLORE
    model_family: str = "unknown"

    def propose(
        self,
        action: StructuredAction,
        parents: List[Program],
        *,
        iteration: int,
    ) -> Program:
        raise NotImplementedError

    # -- helpers --------------------------------------------------------

    def _new_program(
        self,
        code: str,
        *,
        action: StructuredAction,
        parents: List[Program],
        iteration: int,
    ) -> Program:
        parent_id = parents[0].id if parents else None
        generation = (parents[0].generation + 1) if parents else 0
        return Program(
            id=f"cand_{iteration}_{uuid.uuid4().hex[:8]}",
            code=code,
            generation=generation,
            iteration=iteration,
            language=Language.PYTHON,
            parent_id=parent_id,
            created_at=get_timestamp(),
            meta={
                "expert": self.kind.value,
                "model_family": self.model_family,
                "edit_target": action.edit_target,
                "fidelity": int(action.fidelity.value),
                "seed_list": list(action.seed_list),
                "parent_ids": [p.id for p in parents],
                "rationale": action.rationale,
            },
        )

    @staticmethod
    def extract_hyperparams(program: Program) -> Dict[str, Any]:
        """Pull the HYPERPARAMS dict out of a candidate's source code."""
        import ast

        tree = ast.parse(program.code)
        for node in tree.body:
            if isinstance(node, ast.Assign):
                for target in node.targets:
                    if isinstance(target, ast.Name) and target.id == "HYPERPARAMS":
                        try:
                            return ast.literal_eval(node.value)
                        except (ValueError, TypeError):
                            # HYPERPARAMS built with expressions (e.g. 2 ** 8)
                            # or JSON-style literals (true/false/null from the
                            # template's json.dumps round-trip): evaluate the
                            # restricted expression instead.
                            safe_globals = {
                                "__builtins__": {},
                                "true": True, "false": False, "null": None,
                                "True": True, "False": False, "None": None,
                            }
                            return eval(  # noqa: S307 - candidate-internal constants only
                                compile(ast.Expression(node.value), "<hp>", "eval"),
                                safe_globals,
                                {},
                            )
        raise ValueError(f"No HYPERPARAMS assignment found in {program.id}")


# =============================================================================
# GBDT expert (deterministic, no LLM)
# =============================================================================

DEFAULT_GBDT: Dict[str, Any] = {
    "objective": "mse",
    "learning_rate": 0.08,
    "num_leaves": 128,
    "max_depth": 8,
    "colsample_bytree": 0.8,
    "subsample": 0.8,
    "lambda_l1": 100.0,
    "lambda_l2": 500.0,
    "min_data_in_leaf": 50,
    "bagging_freq": 1,
}


class GBDTExpert(ProposalExpert):
    """Deterministic LightGBM config mutation (matches exp2's `mutate` scales).

    Used for explore/mutate/local_hpo actions on the gbdt family. Same
    log-normal perturbation scales as the frozen exp2 pipeline so results
    stay comparable with the measured noise floor.
    """

    model_family = "gbdt"

    def __init__(self, kind: ExpertKind = ExpertKind.MUTATE, rng_seed: int = 0):
        self.kind = kind
        import random

        self._rng = random.Random(rng_seed)

    def propose(
        self,
        action: StructuredAction,
        parents: List[Program],
        *,
        iteration: int,
    ) -> Program:
        base = DEFAULT_GBDT
        if parents:
            try:
                base = self.extract_hyperparams(parents[0])
            except (ValueError, SyntaxError):
                base = dict(DEFAULT_GBDT)

        params = dict(base)
        if self.kind in (ExpertKind.MUTATE, ExpertKind.LOCAL_HPO, ExpertKind.EXPLORE):
            params = self._mutate(params)
        code = _render_template(self.model_family, self.kind.value, params)
        return self._new_program(code, action=action, parents=parents, iteration=iteration)

    def _mutate(self, p: Dict[str, Any]) -> Dict[str, Any]:
        import math

        rng = self._rng
        out = dict(p)

        def lognormal(x, sigma):
            return x * math.exp(rng.gauss(0, sigma))

        out["learning_rate"] = min(0.4, max(0.05, lognormal(float(p["learning_rate"]), 0.20)))
        out["num_leaves"] = int(min(512, max(32, lognormal(float(p["num_leaves"]), 0.25))))
        out["max_depth"] = int(min(12, max(4, p["max_depth"] + rng.randint(-2, 2))))
        out["colsample_bytree"] = min(1.0, max(0.5, p["colsample_bytree"] + rng.gauss(0, 0.06)))
        out["subsample"] = min(1.0, max(0.5, p["subsample"] + rng.gauss(0, 0.06)))
        out["lambda_l1"] = min(800.0, max(20.0, lognormal(float(p["lambda_l1"]), 0.30)))
        out["lambda_l2"] = min(2000.0, max(50.0, lognormal(float(p["lambda_l2"]), 0.30)))
        out["min_data_in_leaf"] = int(min(200, max(5, lognormal(float(p["min_data_in_leaf"]), 0.4))))
        return out


# =============================================================================
# NN expert (LLM-guided, high-variance family)
# =============================================================================

DEFAULT_MLP: Dict[str, Any] = {
    "hidden_dims": [256, 128],
    "dropout": 0.1,
    "learning_rate": 0.001,
    "weight_decay": 0.0001,
    "batch_size": 512,
    "epochs": 20,
    "early_stopping": 5,
    "layer_norm": True,
}


class NNExpert(ProposalExpert):
    """Neural candidate proposer (MLP / temporal blocks).

    Two modes:
    - deterministic config mutation (no LLM, for tests / cheap explore)
    - LLM-guided edit: subclasses or the strategy layer inject
      ``llm_edit_fn(parent_code, action, context_summary) -> new_code``.
      This is the primary path in production; kept as an injectable callable
      so the expert itself stays unit-testable without an LLM.
    """

    model_family = "mlp"

    def __init__(
        self,
        kind: ExpertKind = ExpertKind.EXPLORE,
        rng_seed: int = 0,
        llm_edit_fn: Optional[Any] = None,
        family: str = "mlp",
    ):
        self.kind = kind
        self.model_family = family
        self._llm_edit_fn = llm_edit_fn
        import random

        self._rng = random.Random(rng_seed)

    def propose(
        self,
        action: StructuredAction,
        parents: List[Program],
        *,
        iteration: int,
    ) -> Program:
        if self._llm_edit_fn is not None and parents:
            code = self._llm_edit_fn(parents[0].code, action)
            program = self._new_program(
                code, action=action, parents=parents, iteration=iteration
            )
            program.meta["llm_guided"] = True
            return program

        base = DEFAULT_MLP
        if parents:
            try:
                base = self.extract_hyperparams(parents[0])
            except (ValueError, SyntaxError):
                base = dict(DEFAULT_MLP)
        params = self._mutate(base)
        code = _render_template(self.model_family, self.kind.value, params)
        return self._new_program(code, action=action, parents=parents, iteration=iteration)

    def _mutate(self, p: Dict[str, Any]) -> Dict[str, Any]:
        rng = self._rng
        out = dict(p)
        dims = list(out.get("hidden_dims", [256, 128]))
        # Randomly grow/shrink/shift one layer
        op = rng.choice(["grow", "shrink", "rescale", "toggle_ln"])
        if op == "grow" and len(dims) < 4:
            dims.append(max(32, dims[-1] // 2))
        elif op == "shrink" and len(dims) > 1:
            dims.pop()
        elif op == "rescale":
            idx = rng.randrange(len(dims))
            dims[idx] = int(min(1024, max(32, dims[idx] * rng.choice([0.5, 2.0]))))
        elif op == "toggle_ln":
            out["layer_norm"] = not out.get("layer_norm", True)
        out["hidden_dims"] = dims
        out["dropout"] = min(0.5, max(0.0, out["dropout"] + rng.gauss(0, 0.05)))
        out["learning_rate"] = min(0.01, max(1e-4, out["learning_rate"] * (2 ** rng.gauss(0, 0.5))))
        out["epochs"] = int(min(60, max(5, out["epochs"] + rng.randint(-5, 10))))
        return out


# =============================================================================
# Registry
# =============================================================================


def default_expert_registry(*, rng_seed: int = 0) -> Dict[str, ProposalExpert]:
    """Experts keyed by (expert_kind, model_family) prefix used by the policy."""
    return {
        "gbdt": GBDTExpert(ExpertKind.MUTATE, rng_seed=rng_seed),
        "gbdt_explore": GBDTExpert(ExpertKind.EXPLORE, rng_seed=rng_seed + 1),
        "gbdt_hpo": GBDTExpert(ExpertKind.LOCAL_HPO, rng_seed=rng_seed + 2),
        "mlp": NNExpert(ExpertKind.EXPLORE, rng_seed=rng_seed + 3, family="mlp"),
    }
